// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG.proto

package info.hexin.rpcdemo.protobuf.bytebuffer;


public final class MSG {
	private MSG() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface HostsOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// repeated string name = 1;
		java.util.List<String> getNameList();

		int getNameCount();

		String getName(int index);
	}

	public static final class Hosts extends com.google.protobuf.GeneratedMessage implements HostsOrBuilder {
		// Use Hosts.newBuilder() to construct.
		private Hosts(Builder builder) {
			super(builder);
		}

		private Hosts(boolean noInit) {
		}

		private static final Hosts defaultInstance;

		public static Hosts getDefaultInstance() {
			return defaultInstance;
		}

		public Hosts getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return info.hexin.rpcdemo.protobuf.bytebuffer.MSG.internal_static_msg_Hosts_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return info.hexin.rpcdemo.protobuf.bytebuffer.MSG.internal_static_msg_Hosts_fieldAccessorTable;
		}

		// repeated string name = 1;
		public static final int NAME_FIELD_NUMBER = 1;
		private com.google.protobuf.LazyStringList name_;

		public java.util.List<String> getNameList() {
			return name_;
		}

		public int getNameCount() {
			return name_.size();
		}

		public String getName(int index) {
			return name_.get(index);
		}

		private void initFields() {
			name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < name_.size(); i++) {
				output.writeBytes(1, name_.getByteString(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			{
				int dataSize = 0;
				for (int i = 0; i < name_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(name_.getByteString(i));
				}
				size += dataSize;
				size += 1 * getNameList().size();
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				info.hexin.rpcdemo.protobuf.bytebuffer.MSG.HostsOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return info.hexin.rpcdemo.protobuf.bytebuffer.MSG.internal_static_msg_Hosts_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return info.hexin.rpcdemo.protobuf.bytebuffer.MSG.internal_static_msg_Hosts_fieldAccessorTable;
			}

			// Construct using msg.MSG.Hosts.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts.getDescriptor();
			}

			public info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts getDefaultInstanceForType() {
				return info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts.getDefaultInstance();
			}

			public info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts build() {
				info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
				info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts buildPartial() {
				info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts result = new info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts(this);
				int from_bitField0_ = bitField0_;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					name_ = new com.google.protobuf.UnmodifiableLazyStringList(name_);
					bitField0_ = (bitField0_ & ~0x00000001);
				}
				result.name_ = name_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts) {
					return mergeFrom((info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts other) {
				if (other == info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts.getDefaultInstance())
					return this;
				if (!other.name_.isEmpty()) {
					if (name_.isEmpty()) {
						name_ = other.name_;
						bitField0_ = (bitField0_ & ~0x00000001);
					} else {
						ensureNameIsMutable();
						name_.addAll(other.name_);
					}
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						ensureNameIsMutable();
						name_.add(input.readBytes());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated string name = 1;
			private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureNameIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					name_ = new com.google.protobuf.LazyStringArrayList(name_);
					bitField0_ |= 0x00000001;
				}
			}

			public java.util.List<String> getNameList() {
				return java.util.Collections.unmodifiableList(name_);
			}

			public int getNameCount() {
				return name_.size();
			}

			public String getName(int index) {
				return name_.get(index);
			}

			public Builder setName(int index, String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureNameIsMutable();
				name_.set(index, value);
				onChanged();
				return this;
			}

			public Builder addName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureNameIsMutable();
				name_.add(value);
				onChanged();
				return this;
			}

			public Builder addAllName(java.lang.Iterable<String> values) {
				ensureNameIsMutable();
				super.addAll(values, name_);
				onChanged();
				return this;
			}

			public Builder clearName() {
				name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			void addName(com.google.protobuf.ByteString value) {
				ensureNameIsMutable();
				name_.add(value);
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:msg.Hosts)
		}

		static {
			defaultInstance = new Hosts(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:msg.Hosts)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_msg_Hosts_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_msg_Hosts_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\tMSG.proto\022\003msg\"\025\n\005Hosts\022\014\n\004name\030\001 \003(\tB"
				+ "\n\n\003msgB\003MSG" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_msg_Hosts_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_msg_Hosts_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_msg_Hosts_descriptor, new java.lang.String[] { "Name", }, info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts.class,
						info.hexin.rpcdemo.protobuf.bytebuffer.MSG.Hosts.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
